# File uplaod
filesDir: ./data/files

# Database settings.
database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./data/db

# Migration settings
flyway:
  locations:
    - db/migration

# Logging settings.
logging:
  level: INFO
  loggers:
    io.dunham.raku: DEBUG
    org.hibernate.SQL:
      level: DEBUG
    io.dropwizard.jersey.jackson: DEBUG
