# File uplaod
filesDir: ./data/files

# Database location
databaseLocation: ./data/db

# Logging settings.
logging:
  level: INFO
  loggers:
    io.dunham.raku: DEBUG
    io.dropwizard.jersey.jackson: DEBUG
    org.skife.jdbi.v2: TRACE
