# File uplaod
filesDir: ./data/files

# Database location
databaseLocation: ./data/db

# Backup directory
#backupDir: ./data/backups

# Server settings
server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1

# Logging settings.
logging:
  level: INFO
  loggers:
    io.dunham.raku: DEBUG
    io.dropwizard.jersey.jackson: DEBUG
    org.skife.jdbi.v2: TRACE
